### PR TITLE
Add Generic Application Block to FRAM Map

### PR DESCRIPTION
**Pull request by lthiery**
This is intended to allow a user to store more or less arbitrary data an FRAM slot. It would be up to the application layer to derive and determine validity of the data in the block.

### CODE REVIEW

**Comment by lthiery** [comment]
@terrillmoore did i do it right for immediate release?

**Comment by terrillmoore** [comment]
Hi, there's a release checklist in the tickets marked 'release'. See #246 for an example. Need to update `library.properties`, `README.me`, and the version in the header file (for introspection).

**Comment by terrillmoore** [comment]
(I'd do the changes, but I have to run a meeting for the next two hours.)

**Comment by lthiery** [comment]
I _think_ I did it? But I have referenced this PR in the release history while it seems like you normally do issues. Should I create an issue about this PR or this fine?

**Comment by terrillmoore** [comment]
Looks right to me! I'll merge now and release.

**Pull request merged**
