### PR TITLE
Fix #350: added library support for STM32Lxx watchdog timer

### LINKED ISSUE #350: add library support for STM32Lxx watchdog timer

### PR DESCRIPTION
**Pull request by Pranau-R**

### CODE REVIEW

**Review by dhineshkumarmcci — CHANGES_REQUESTED** [review]
looks good with watchdog timer portion. we also need to get the README updated and versioning changes done.

**Comment by Pranau-R** [comment]
> looks good with watchdog timer portion. we also need to get the README updated and versioning changes done.

I have updated the README with watchdog timer changes and versioning has been done.

**Comment by dhineshkumarmcci** [comment]
@Pranau-R adding Watchdog is a new feature, the version change should have incremental in the minor field and not in the field patch, please change version from 0.22.1 to 0.23.0

**Comment by Pranau-R** [comment]
> @Pranau-R adding Watchdog is a new feature, the version change should have incremental in the minor field and not in the field patch, please change version from 0.22.1 to 0.23.0

Sorry for the inconvenience caused. I have changed the version from 0.22.1 to 0.23.0

**Comment by dhineshkumarmcci** [comment]
good to go for the release

**Review by dhineshkumarmcci — APPROVED** [review]

**Pull request merged**
