### PR TITLE
Add ReadAnalog(channel) method and use this method to read voltage.

### PR DESCRIPTION
**Pull request by chwon64**
This is for #117

### CODE REVIEW

**Comment by chwon64** [comment]
I added Catena 4801 support code. Please review it.
Do you know what multiplication factor use?

**Comment by dhineshkumarmcci** [comment]
The multiplication factor for Catena 4801 is similar to Catena 4612.
We have tested the Catena 4801 support code using OTII for different voltages from 2.00 V to 3.75 V.
We were able to monitor the respective VBat values in serial monitor for various input voltages.

**Comment by chwon64** [comment]
That's good. Thanks Dhinesh for testing Catena 480x support code.
Terry, can you merge pull request?

**Comment by terrillmoore** [comment]
Yes, thanks.

**Pull request merged**
