### PR TITLE
Fix #261: support for FRAM buffer to write/read more than 255 bytes

### LINKED ISSUE #261: FRAM reads > 256 bytes problematic
It appears that the low level FRAM driver `Catena_Mb85rc64ta::read()` and `write()` don't support buffers > 255 bytes. This needs to be changed for secure element support.

### PR DESCRIPTION
**Pull request by dhineshkumarmcci**
Added support for low level FRAM driver `Catena_Mb85rc64ta::read()` and `write()` to read/write > 255 bytes.

### CODE REVIEW

**Comment by terrillmoore** [comment]
We can't merge unless we update the version number. Please update at least the local rev. My convention is only to update x.y.z when we actually do a release, so we must update patch. Also, please document in README.md.

**Review by terrillmoore — CHANGES_REQUESTED** [review]
See comment. Need version change and README update.

**Comment by dhineshkumarmcci** [comment]
@terrillmoore Made the version changes and updated the README

**Comment by terrillmoore** [comment]
Merged, thanks!

**Pull request merged**
